:construction_worker: feat(ci): Add new composite action for building maven plugin
Candy-Doc/candy-doc-maven-plugin pull request #119
Opened 2022-04-25 08:43 UTC by Tifloz

# Pull request for Candy-doc

## Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../../CONTRIBUTING.md) to
this repository.

- [ ] Make sure you are requesting to **pull a feature/bugfix branch** (right
  side). Don't request your master!
- [ ] Make sure you are making a pull request against the **main branch** (left
  side).
- [ ] Check the commit's or even all commits' message styles matches our
  requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit
  test.

## Description

I want to avoid code duplication so we need to make a composite action for testing and building

❤️ Thank you!

2022-04-26 12:34 UTC, M4gie approved these changes

2022-04-29 09:21 UTC, ecattez requested changes

2022-04-29 09:21 UTC, ecattez commented on .github/workflows/package.yml
> +  tests_and_build:
Don't do composite action if you don't have multiple use cases. Execute tests and build only on feature branches. (main is obviously good)

2022-05-02 08:17 UTC, Tifloz commented
We finally don't need a composite action in the project for the moment

2022-05-02 08:17 UTC, closed without merging