:construction_worker: fix: Move PR template to the .github/ root
Candy-Doc/candy-doc-maven-plugin pull request #121
Opened 2022-04-25 09:35 UTC by Tifloz

# Pull request for Candy-doc

## Your checklist for this pull request

🚨 Please review the [guidelines for contributing](Documents/Candy-Doc/candy-doc-maven-plugin/CONTRIBUTING.md) to
this repository.

- [ ] Make sure you are requesting to **pull a feature/bugfix branch** (right
  side). Don't request your master!
- [ ] Make sure you are making a pull request against the **main branch** (left
  side).
- [ ] Check the commit's or even all commits' message styles matches our
  requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit
  test.

## Description

Just move the template to be able to auto-setup it in GitHub

❤️ Thank you!

2022-04-25 09:40 UTC, ecattez requested changes

2022-04-25 09:40 UTC, ecattez commented on .github/pull_request_template.md
> +🚨 Please review the [guidelines for contributing](Documents/Candy-Doc/candy-doc-maven-plugin/CONTRIBUTING.md) to
Weird path ?

2022-04-25 09:56 UTC, ecattez submitted a review, later dismissed

2022-04-26 12:33 UTC, M4gie approved these changes

2022-04-29 09:21 UTC, ecattez approved these changes

2022-04-29 09:22 UTC, merged