:memo: Enhance README.md
Candy-Doc/candy-doc-maven-plugin pull request #201
Opened 2023-05-26 12:55 UTC by Yugo-Cartron

# Pull request for Candy-doc

## Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../../CONTRIBUTING.md) to
this repository.

- [ ] Make sure you are requesting to **pull a feature/bugfix branch** (right
  side). Don't request your master!
- [ ] Make sure you are making a pull request against the **main branch** (left
  side).
- [ ] Check the commit's or even all commits' message styles matches our
  requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit
  test.

## Description

Enhance the README.md
  - Fixing links 
  - Adding new contributors
  - Adding sections
  - Removing some text

❤️ Thank you!

2023-05-29 09:09 UTC, AntonyDerache submitted a review, later dismissed
Good 👍 

Idea: maybe in the future it could be interesting to link a small "demo" project like the bookshelf but a bit more developed. To give an implementation example of the plugin

2023-05-30 07:45 UTC, ctacquet requested changes

2023-05-30 07:45 UTC, ctacquet commented on README.md
> +](#-candy-doc-maven-plugin-)
Il y a trop de passage à la ligne.

Pourquoi tu veux déplacer le ToC ?

2023-05-30 07:45 UTC, ctacquet commented on README.md
> +# Roadmap 🗺️
Je pense que tu as retiré un # en trop

2023-05-30 13:56 UTC, ecattez requested changes

2023-05-30 13:56 UTC, ecattez commented on README.md
> +You can display your documentation by opening the `index.html` file in your favorite browser.
I think we should link this part to the other projects to avoid sync problems between the way it works now and the future of candy-cli / candy-board.

2023-05-30 13:56 UTC, ecattez commented on README.md
> +
Too much lines

2023-06-07 11:00 UTC, ecattez approved these changes
I think the annotations could have their own javadoc to keep definitions close to the different concepts. Then, these javadoc could update the README.md. I might create an issue for that. What do you think ?

2023-06-07 14:46 UTC, Yugo-Cartron commented
> I think the annotations could have their own javadoc to keep definitions close to the different concepts. Then, these javadoc could update the README.md. I might create an issue for that. What do you think ?

To our opinion, we thought about creating a markdown file called _DDDConcepts.md_, which will be dedicated to explain all the DDD concepts and their allowed dependencies.

2023-06-08 09:31 UTC, merged

2023-06-08 09:34 UTC, Tifloz commented
:tada: This PR is included in version 2.2.0 :tada:

The release is available on:
- [GitHub release](https://github.com/Candy-Doc/candy-doc-maven-plugin/releases/tag/v2.2.0)
- `v2.2.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: