📝 docs: Update documentation
Candy-Doc/candy-doc-maven-plugin pull request #99
Opened 2022-04-04 08:59 UTC by Tifloz

2022-04-15 09:22 UTC, ecattez requested changes
Removes lombok and pom because it is not the PR scope

2022-04-21 13:50 UTC, mderoullers requested changes
Les screenshots ne doivent pas être dans les resources de ton logiciel selon moi. Elles concernent le Readme pas le code, je trouve ça bizarre de les avoir là. 
Je les aurais mis plutôt dans un dossier `/assets` à la racine du repo

2022-04-22 09:54 UTC, ecattez requested changes

2022-04-22 09:54 UTC, ecattez commented on CONTRIBUTING.md
> +## How to set up your PGP key [*Windows*]
Link a reference to github documentation

2022-04-22 09:54 UTC, ecattez commented on CONTRIBUTING.md
> +## How to set up your PGP key [*Windows*]
Move PGP section below the contributing rules

2022-04-29 09:17 UTC, ecattez submitted a review, later dismissed

2022-04-29 13:16 UTC, M4gie approved these changes

2022-04-29 13:16 UTC, Michiels96 approved these changes

2022-04-29 13:19 UTC, merged

2022-05-16 13:38 UTC, Tifloz commented
@all-contributors please add @Tifloz  for tutorial